apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrental
  namespace: rental-service
spec:
  template:
    spec:
      containers:
      - name: carrental
        imagePullPolicy: IfNotPresent
