apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-angular
  namespace: rental-service
spec:
  template:
    spec:
      containers:
      - name: frontend-angular
        imagePullPolicy: IfNotPresent
