apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: rental-service
  labels:
    app: postgres
type: Opaque
# Credentials en plain text (stringData les encode automatiquement)
stringData:
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "dbpass"
  POSTGRES_DB: "dbcar"
  # Properties pour Spring Boot
  SPRING_DATASOURCE_USERNAME: "dbuser"
  SPRING_DATASOURCE_PASSWORD: "dbpass"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dbcar"
