apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rental-service

resources:
  - ../../base
  - ingress-minikube.yaml

patchesStrategicMerge:
  - patches/carrental-image-pull.yaml
  - patches/frontend-image-pull.yaml
  - patches/auction-image-pull.yaml
